### PR TITLE
[mssqldef] Support Unicode string literal

### PR DESCRIPTION
**Pull request by odz**
Support Unicode string literal like N'string' in SQL Server.

### CODE REVIEW

**Review by k0kubun — APPROVED** [review]
Thanks!

**Comment by k0kubun** [comment]
You've made a lot of good contributions to mssqldef. I'm open to making you a maintainer. Let me know if you're interested.

**Comment by odz** [comment]
Thank you. I will gladly be a maintainer.

**Comment by k0kubun** [comment]
Thanks! I invited you to be a collaborator.

---

My expectations for a maintainer are:

* You're expected to push commits to master without asking for my reviews.
  * No pull request is preferable in most cases unless you want reviews.
  * If you want to leave any description, please write that down in commit messages.
* You're also expected to cut a release after your changes.
  * If you push a change that impacts any behavior, you're expected to cut a release at least once on the same day.
  * It's as easy as updating CHANGELOG.md and running `git tag v0.x.y && git push origin --tags && git push origin master` at the latest master.
  * About versioning, please bump a minor version if you think it's a release with significant or breaking changes, or a teeny version if it's backward-compatible and insignificant. For now, please keep the major version (v0) as is.
* If any issue that is related to your area or change is filed, I would like you to fix and close it.

That's it. Please let me know if you have any questions :)

**Pull request merged**
