### PR TITLE
Support check constraint for tables in non-public schema

### PR DESCRIPTION
**Pull request by yuku**
This PR makes it possible to define `CHECK` constraints for tables in non-public schema:

```sql
CREATE TABLE test.dummy (
  min_value INT CHECK (min_value > 0),
  max_value INT CHECK (max_value > 0),
  CONSTRAINT min_max CHECK (min_value < max_value)
);
```

### CODE REVIEW

**Comment by yuku** [comment]
I'm going to fix tests for postgres 10 and 11.

**Comment by k0kubun** [comment]
I think it's irrelevant and I already fixed it. Can we just merge this?

**Comment by yuku** [comment]
Ah, thanks.
Please merge this if you don't find any issues 😄

**Comment by yuku** [comment]
@k0kubun I'm using postgres 14 in my project. Can I add postgres 13 and 14 to test matrix?

**Comment by k0kubun** [comment]
Sure.

**Comment by yuku** [comment]
Thanks. I'm going to submit another PR later. 👋

**Review by k0kubun — APPROVED** [review]
Thank you!

**Pull request merged**
