### PR TITLE
Wasm

### PR DESCRIPTION
**Pull request by konsumer**
Related to #45 

This includes basic wasm build to wrap just the DDL stuff for the web. You can use it to make a live demo of what the CLI does, or just use it as a web-based tool for diffing SQL.

I tried getting proper error-handling working, and get it running better in node, but haven't worked it out, so I will probly just leave this as it is, and switch my node-lib to wrap the go CLI.

I think there are lots of benefits to compiling to wasm, like running in many environments, faster runtimes, etc, but I think maybe go-wasm isn't quite there, or at least I can't work it out, yet.

Thats said, this is still useful as a web-based demo.

### CODE REVIEW

**Comment by k0kubun** [comment]
Thank you for filing a PR :)

Because it worked out without touching the sqldef's internal packages, how about separating the project repository for this layer for now? I think it is helpful for fixing the CI failure at least.

I created a sqldef organization https://github.com/sqldef now. The repository placement would look like:

* github.com/sqldef/sqldef: This repository will be transferred to that place
* github.com/sqldef/sqldef-wasm (or whatever you like): This PR's content will go to this place

If you're okay with it, I'll make the transfer and invite you to the organization for developing the sqldef-wasm repository.

**Comment by k0kubun** [comment]
see also: https://github.com/k0kubun/sqldef/issues/45#issuecomment-549009301

**Comment by k0kubun** [comment]
Okay, I saved your work as https://github.com/sqldef/sqldef-wasm, and sent an invitation to the organization now. Thank you!

**Comment by konsumer** [comment]
I'm not sure I understand the CI fail, looks like it's not aware of the `syscall/js` that's part of the stdlib. `go get -t ./...` failed for me, too, which is why I had to seperate the make target, because of this error:

```
go get -t ./...
web/sqldef-wasm.go:8:3: build constraints exclude all Go files in /usr/local/opt/go/libexec/src/syscall/js
make: *** [deps] Error 1
```
When I removed `deps` from the make deps, it worked fine.

Maybe a better way to do this would be to tag them [like this](https://www.reddit.com/r/golang/comments/75ghpk/how_to_exclude_code_from_compilation/) so you have to use `go build -tags=wasm`

**Comment by konsumer** [comment]
Or just I can just use the seperate repo. That's fine, too. :)

**Comment by k0kubun** [comment]
I feel it's easier to use a repository instead of a tag (outside the default branch) or non-default branch because it's visible out of the box.

The repository separation might be also useful for org-level GitHub pages like `sqldef/sqldef.github.io`.

**Comment by konsumer** [comment]
I made a repo for the node wrapper, too. I can also help with the website, if you like. Maybe put a demo inline!

**Comment by k0kubun** [comment]
I put a placeholder https://github.com/sqldef/sqldef.github.io.

Please feel free to modify these repositories as you like! (For example, just moving the current sqldef-wasm to there, or changing it to a repository publishing wasm to the repository to avoid including .go in GitHub Pages)

**Comment by konsumer** [comment]
I noticed it was missing, but missed the comment-change till now. Thought maybe I should recreate, but I totally agree. I think the web/wasm version makes a nice demo, as it is, and you can just link to that in READMEs, to show off the SQL diffing. Let me know if you want other content on the landing page or whatever. I don't know what your frontend experience-level is, but I am pretty comfortable making revisions & additions, and I can set it up however you like. I also made a [node library](https://github.com/sqldef/node-sqldef) that should help javascript-people use your tool. It downloads the correct compiled version, on install, and wraps it with a simple API. I didn't publish on npm because I thought you might want to, but I think it's ready to go (tested on postgres & react, and seems to work alright.)

**Comment by k0kubun** [comment]
> I noticed it was missing, but missed the comment-change till now. Thought maybe I should recreate, but I totally agree. I think the web/wasm version makes a nice demo, as it is, and you can just link to that in READMEs, to show off the SQL diffing. Let me know if you want other content on the landing page or whatever.

Yeah, you already implemented the amazing capability for demonstrating sqldef at the landing page. Right now I don't have enough time to make it like a landing page, but such a change would be nice to have, as we already have the wonderful thing to be displayed there.

To move it forward, I renamed the repository and made it possible to see it from https://sqldef.github.io, which is now linked from the sqldef repository's description.

>  I also made a node library that should help javascript-people use your tool. It downloads the correct compiled version, on install, and wraps it with a simple API. I didn't publish on npm because I thought you might want to, but I think it's ready to go (tested on postgres & react, and seems to work alright.)

Thank you! I may ask to share the maintenance/release responsibility when I'm ready if you're okay, but I'm not so fluent in node yet. Please feel free to publish it to npm with the name you like.

**Comment by konsumer** [comment]
> To move it forward, I renamed the repository and made it possible to see it from https://sqldef.github.io, which is now linked from the sqldef repository's description.

Sounds good. I will update the demo link in the node-project. I feel like it would be cool to really push how it's useful with a short intro, then link to the github page for more detail. When I have some time. I'll add some stuff.

> I may ask to share the maintenance/release responsibility when I'm ready if you're okay, but I'm not so fluent in node yet. Please feel free to publish it to npm with the name you like.

I'll publish as "sqldef" (which isn't taken) but am happy to transfer ownership, any time. Also, if you have an npm account (it's free, and looks like "sqldef" username isn't taken either, if you want that) I can just add you, so we are both owners. I still think wasm would be best for node (and many others) so if I can work it out with go, it might be worth moving to that, but it's useful enough as it is. It has some fancy CLI/config stuff that will make it awesome for replacing knex migrations in node projects.

This is only vaguely-related, but I'd love to add (at least DDL diffing) support for other databases, too, as I get better with go. It'd be cool if I could use sqlite locally, like I currently do with knex. I could see sqldef + a nice cross-database SQL lib (like any-db for example) being a super-awesome sql-literate cross-db way to manage & query a database.

Should we delete the branch attached to this issue? (`wasm`)

**Comment by k0kubun** [comment]
> Also, if you have an npm account (it's free, and looks like "sqldef" username isn't taken either, if you want that) I can just add you, so we are both owners. 

Do you think taking the "sqldef" username is helpful? For now I created my account as "k0kubun" and enabled 2FA. Please invite me to owners when you have a chance.

> I still think wasm would be best for node (and many others) so if I can work it out with go, it might be worth moving to that, but it's useful enough as it is.
>
> This is only vaguely-related, but I'd love to add (at least DDL diffing) support for other databases, too, as I get better with go. It'd be cool if I could use sqlite locally, like I currently do with knex. I could see sqldef + a nice cross-database SQL lib (like any-db for example) being a super-awesome sql-literate cross-db way to manage & query a database.

:+1:

> Should we delete the branch attached to this issue? (wasm)

Please do whatever you like as it's your fork's branch. We could also create another repository if we want to separate wasm work from sqldef.github.io repository.

**Comment by konsumer** [comment]
> Do you think taking the "sqldef" username is helpful? For now I created my account as "k0kubun" and enabled 2FA. Please invite me to owners when you have a chance.

Nah, I use "konsumer" on npm. Just mentioning that it's an option, if it's the only npm thing. Added you as owner.

> We could also create another repository if we want to separate wasm work from sqldef.github.io repository.

Either way is fine with me. github treats org-projects differently than others, in that the website has to go in master at root dir. I'm really not worried about it, either way, though.

**Pull request closed without merging**
