### PR TITLE
Support deferrable unique constraint for PostgreSQL

### PR DESCRIPTION
**Pull request by yuku**
This PR *will* make psqldef handle DDL like:

```sql
alter table dummy add constraint dummy_uniq unique (column_a, column_b) deferrable initially deferred;
```

[PostgreSQL: Documentation: 14: ALTER TABLE](https://www.postgresql.org/docs/14/sql-altertable.html)

### CODE REVIEW

**Comment by yuku** [comment]
@k0kubun In 52f48098309 I tried to fix the sqlparser to accept the expected DDL, but when I run the tests I added, I get syntax errors. I spent several hours trying to debug it, but I still haven't been able to, partly because I'm new to goyacc.

Can you see what I'm missing?

By the way, if you think it is much easier for you to write another patch by your self from scratch rather than reviewing my code, please feel free to close this PR 🙏 

```
cd cmd/psqldef && PGHOST=127.0.0.1 PGSSLMODE=disable go test -v -run TestPsqldefAddConstraintUnique
=== RUN   TestPsqldefAddConstraintUnique
    psqldef_test.go:668: failed to execute './psqldef -Upostgres psqldef_test --file schema.sql' (error: 'exit status 1'): `found syntax error when parsing DDL "alter table dummy add constraint dummy_uniq unique (column_a, column_b) not deferrable initially immediate": syntax error at position 87 near 'deferrable'
        `
    psqldef_test.go:668: expected '-- Nothing is modified --
        ' but got 'found syntax error when parsing DDL "alter table dummy add constraint dummy_uniq unique (column_a, column_b) not deferrable initially immediate": syntax error at position 87 near 'deferrable'
        '
...
```

**Comment by k0kubun** [comment]
> I tried to fix the sqlparser to accept the expected DDL, but when I run the tests I added, I get syntax errors. I spent several hours trying to debug it, but I still haven't been able to, partly because I'm new to goyacc.

You declared new tokens on the parser side, but you didn't let the lexer generate the tokens. So those keywords were recognized as if they were normal identifiers instead of keywords. Fixing it is as simple as https://github.com/k0kubun/sqldef/pull/186/commits/16aa6293d305cad957657b680ddca0ec27f0b499.

You also need to touch `schema/ast.go` and `schema/parser.go` to complete the generator implementation. I'm going to However, it's just specific to the current codebase that's a bit messed up. So it's not your fault. I plan to change the architecture of how `schema` package works, but the work has not been completed yet. Anyway it's fixed in https://github.com/k0kubun/sqldef/pull/186/commits/53ef6c44ae510aea8b38c685d3e44dd1aaed67cc. I needed to delete a test case because:

```
2022/01/21 21:09:40 pq: constraint declared INITIALLY DEFERRED must be DEFERRABLE
```

**Review by k0kubun — APPROVED** [review]
Thanks!

**Comment by k0kubun** [comment]
Released as v0.11.24.

**Pull request merged**
