### PR TITLE
mssqldef: support select in trigger

### PR DESCRIPTION
**Pull request by ytakaya**
This allow the `SELECT ...` statement in the trigger.

In addition, I fixed trigger statement so that multiple events can be defined.
like
```
CREATE TRIGGER ... AFTER INSERT, DELETE ...
```

This pull request is based on https://github.com/k0kubun/sqldef/pull/141.

### CODE REVIEW

**Comment by ytakaya** [comment]
@k0kubun 
Now I'm done implementing all the trigger statements I wanted.
The following statement is added.
- `DECLARE ...` (https://github.com/k0kubun/sqldef/pull/137)
- `OPEN cursor`, `FETCH cursor ...`, `CLOSE cursor` (https://github.com/k0kubun/sqldef/pull/138)
- `WHILE ...` (https://github.com/k0kubun/sqldef/pull/139)
- `IF ... ELSE ...` (https://github.com/k0kubun/sqldef/pull/141)
- `SELECT ...` (this pull request)

As discussed in the first pull request, I implemented the trigger body to be held in `[]string`.

**Comment by k0kubun** [comment]
Thank you! I'll allocate some time to review all that. I'm planning to do that by the end of this month, but if you need a binary release for your usage earlier than it, I can cut a beta release for it while you're waiting for the review. Please let me know if you need it.

**Comment by ytakaya** [comment]
I don't need the binary urgently, so it can be done after the review.
I appreciate your help with the review!

**Comment by k0kubun** [comment]
re-created at https://github.com/k0kubun/sqldef/pull/148 to minimize the diff

**Comment by k0kubun** [comment]
looks good to me. Thank you so much :raised_hands:

**Comment by ytakaya** [comment]
Thanks for your review!

**Pull request merged**
