### PR TITLE
Support SQLite3

### PR DESCRIPTION
**Pull request by mattn**
Add support of SQLite3. I dropped some tests because of sqlite3 does not support `ALTER TABLE foo DROP COLUMN`.

### CODE REVIEW

**Comment by k0kubun** [comment]
Great work, thank you :clap: :clap: :clap:

CI results hadn't been available in this PR, but I fixed the issue. Could you take a look at the test failures of mysqldef https://travis-ci.org/github/k0kubun/sqldef/builds/731535505?

**Comment by mattn** [comment]
Thank you. I'll look into it tonight.

**Comment by mattn** [comment]
Fixed. 👍

**Review by k0kubun — APPROVED** [review]
Thanks a lot! :tada:

**Comment by k0kubun** [comment]
[Successfully released](https://travis-ci.org/github/k0kubun/sqldef/builds/732139836) as v0.7.0. https://github.com/k0kubun/sqldef/releases/tag/v0.7.0

**Pull request merged**
